### ISSUE TITLE
Update with Pg14

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgconfig-ce#4]

**Comment by anayrat** [comment]
up :)

**Comment by rustprooflabs** [comment]
Woah, and Pg15 beta 1 is out now... Well.  Time has gone by!

Looks like #5 had the start to it, probably needs review against production-ready pg14.

**Comment by rustprooflabs** [comment]
Merged #5 and deployed.

**Comment by anayrat** [comment]
Thanks!
